### ISSUE TITLE
Print to console

### ISSUE THREAD

**Issue by Y-Less** [maddinat0r/samp-log-core#7]
Would be good if as well as writing things to file (which is good) they could be shown in the console for fast debugging.  Maybe even with separate filter levels if #5 gets implemented - send `ERROR` and `WARNING` to files, `DEBUG` to the console, for example.

**Comment by maddinat0r** [comment]
Added per loglevel (7759b27241b92dc44a8aabc4deef2cfe1acdfd00) and per logger (c447281efccfd907cdf8337398d07b50201d6739) options for printing messages to consoles.
